name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间0点执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限配置[5](@ref)

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0  # 获取完整提交历史[5](@ref)

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Contribution Snake'
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
