name: generate animation
on:
schedule:
  - cron: "0 */24 * * *"
workflow_dispatch:

jobs:
generate:
  runs-on: ubuntu-latest
  steps:
    - uses: Platane/snk/svg-only@v3
      with:
        github_user_name: universero
        outputs: dist/github-contribution-grid-snake.svg
